name = "todo-api"
type = "javascript"

account_id = "你的 Cloudflare 账户 ID"
zone_id = "你的域名区域 ID" # 可选
route = "https://api.todo.one-mail.us.kg/*" # 部署路由

# 使用 KV 存储
kv_namespaces = [
  { binding = "TODOS", id = "8ec7189f31774a05b62eb4267e8f62c2" }
]
